"""ss

Revision ID: 0018f816fb9c
Revises: 86c912c7a838
Create Date: 2022-03-16 15:16:58.666096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0018f816fb9c'
down_revision = '86c912c7a838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    pass
    # ### end Alembic commands ###
