"""s

Revision ID: 03f8d808fceb
Revises: 0018f816fb9c
Create Date: 2022-03-16 15:20:05.788204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f8d808fceb'
down_revision = '0018f816fb9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
