"""Added users table

Revision ID: 0559f427dbd1
Revises: 12828affc099
Create Date: 2022-03-23 21:13:47.222660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0559f427dbd1'
down_revision = '12828affc099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
