"""netabw

Revision ID: 12828affc099
Revises: eeb3790d970b
Create Date: 2022-03-16 15:27:24.870715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12828affc099'
down_revision = 'eeb3790d970b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
