"""ks

Revision ID: 2494d6aa5bf0
Revises: 7ab5cfc0e64c
Create Date: 2022-03-16 15:24:09.008390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2494d6aa5bf0'
down_revision = '7ab5cfc0e64c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
