"""ks

Revision ID: 7ab5cfc0e64c
Revises: 03f8d808fceb
Create Date: 2022-03-16 15:22:26.370053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab5cfc0e64c'
down_revision = '03f8d808fceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
