"""delete posts

Revision ID: 816ce4f97a48
Revises: 38911d1bb41b
Create Date: 2022-03-16 14:27:49.273069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '816ce4f97a48'
down_revision = '38911d1bb41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
