"""new

Revision ID: eeb3790d970b
Revises: 2494d6aa5bf0
Create Date: 2022-03-16 15:25:21.961249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb3790d970b'
down_revision = '2494d6aa5bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
